export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
// ticker
export const UPDATE_BID = 'UPDATE_BID';
export const UPDATE_BID_SIZE = 'UPDATE_BID_SIZE';
export const UPDATE_ASK = 'UPDATE_ASK';
export const UPDATE_ASK_SIZE = 'UPDATE_ASK_SIZE';
export const UPDATE_DAILY_CHANGE = 'UPDATE_DAILY_CHANGE';
export const UPDATE_DAILY_CHANGE_RELATIVE = 'UPDATE_DAILY_CHANGE_RELATIVE';
export const UPDATE_LAST_PRICE = 'UPDATE_LAST_PRICE';
export const UPDATE_VOLUME = 'UPDATE_VOLUME';
export const UPDATE_HIGH = 'UPDATE_HIGH';
export const UPDATE_LOW = 'UPDATE_LOW'
// order book
export const UPDATE_ORDER_BOOK = 'UPDATE_ORDER_BOOK';
export const UPDATE_TRADES = 'UPDATE_TRADES';
